import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const source = readFileSync(new URL('./ai-automation.js', import.meta.url), 'utf8')
const styles = readFileSync(new URL('./ai-automation.css', import.meta.url), 'utf8')

test('AI prompt sends on Enter while preserving IME and multiline input', () => {
  assert.match(source, /@keydown="handlePromptKeydown"/)
  assert.match(source, /event\.key !== 'Enter' \|\| event\.shiftKey \|\| event\.isComposing/)
  assert.match(source, /event\.preventDefault\(\)\s+sendPrompt\(\)/)
  assert.match(source, /chatStream\.value\.scrollTop = chatStream\.value\.scrollHeight/)
  assert.match(source, /pendingUserMessages\.value\.push/)
  assert.match(source, /正在发送/)
  assert.match(source, /Enter 发送/)
  assert.match(source, /Shift \+ Enter 换行/)
})

test('AI high-risk plans open beside the chat and remain readable', () => {
  assert.match(source, /reviewPlan.*approval_required.*blocked/)
  assert.match(source, /selectChatPlan\(reviewPlan\)/)
  assert.match(source, /class="ai-chat-plan-drawer"/)
  assert.match(source, /requestPlanExecution\(activeChatPlan\)/)
  assert.match(source, /armedPlanID\.value !== plan\.id/)
  assert.match(source, /confirmation\.value = plan\.confirmation_phrase\s+}\s+executePlan\(plan\)/)
  assert.match(source, /再次确认并执行/)
  assert.match(source, /必须逐字二次确认，未确认绝不提交/)
  assert.match(source, /blocked: '预检已阻止'/)
  assert.match(source, /class="ai-inline-plan-error"/)
  assert.match(source, /查看处理方案/)
  assert.match(source, /查看异常分析/)
  assert.match(source, /预检结果与处理方案/)
  assert.match(source, /异常分析与恢复方案/)
  assert.match(source, /window\.setInterval\(pollExecution, 5000\)/)
  assert.match(source, /recoveryPlan.*parent_plan_id/s)
  assert.match(source, /selectChatPlan\(recoveryPlan\)/)
  assert.match(source, /phaseLabel\(step\.phase\)/)
  assert.match(source, /完整操作流程/)
  assert.match(source, /验证标准与失败处理/)
  assert.match(source, /手动分析可用 · 自动化未启用/)
  assert.match(styles, /\.ai-message p\{[^}]*font-size:14px/)
  assert.match(styles, /\.ai-chat-input textarea\{[^}]*font-size:14px/)
  assert.match(source, /<header v-if="tab!=='copilot'" class="ai-hero">/)
  assert.match(styles, /\.content:has\(> \.ai-page\.copilot-mode\)\{[^}]*overflow-y:hidden/)
  assert.match(styles, /\.ai-copilot\.withPlan\{[^}]*grid-template-columns/)
  assert.match(styles, /\.ai-chat-stream\{[^}]*overflow-y:auto/)
  assert.match(styles, /\.ai-plan-workflow>ol/)
})

test('AI approval modal never submits a click event as the plan', () => {
  assert.match(source, /const plan = planInput\?\.id \? planInput : approvalPlan\.value/)
  assert.match(source, /@click="executePlan\(\)"/)
  assert.doesNotMatch(source, /@click="executePlan"/)
  assert.match(source, /const message = err\.message\s+await load\(true\)\s+if \(approvalPlan\.value\?\.id === plan\.id\) approvalPlan\.value = null\s+resetApprovalInputs\(\)\s+error\.value = message/)
  assert.match(source, /有效至 \{\{ shortDate\(approvalPlan\.expires_at\) \}\}/)
})

test('AI workflow progress, checkpoints, pause and recovery stay beside chat', () => {
  assert.match(source, /workflows: \[\]/)
  assert.match(source, /const activeChatWorkflow = computed/)
  assert.match(source, /任务编排与实时状态/)
  assert.match(source, /activeChatWorkflow\.operations/)
  assert.match(source, /operation\.depends_on\?\.length \? '等待前置步骤' : '等待执行'/)
  assert.match(source, /最近检查点/)
  assert.match(source, /\/workflows\/pause/)
  assert.match(source, /\/workflows\/resume/)
  assert.match(source, /暂停只阻止后续步骤/)
  assert.match(source, /chatPlanID\.value = plan\.id/)
  assert.match(styles, /\.ai-runtime-workflow/)
  assert.match(styles, /\.ai-workflow-checkpoints/)
})
